image: circleci/node:8-browsers

variables:
  # CODECLIMATE_REPO_TOKEN: ... # set in CI secret variables
  CODECLIMATE_API_HOST: https://codebeat.co/webhooks/code_coverage
  APP_DEPLOY_SLUG: pr-$CI_COMMIT_REF_SLUG-wcn.bscode.net

stages:
  - build
  - test
  - integration
  - deploy

cache:
  policy: pull
  untracked: true

build: # This job is just to generate and push to the cache
  stage: build
  cache:
    policy: pull-push
    untracked: true
  artifacts:
    paths:
      - dist/
  script:
    - yarn install --frozen-lockfile
    - yarn build --progress=false

unit-tests:
  stage: test
  artifacts:
    paths:
      - coverage/
  script:
    - yarn test:ci --progress=false
    - yarn codeclimate-test-reporter < coverage/lcov.info

linting:
  stage: test
  script:
    - yarn lint

coverage:
  stage: integration
  script:
    - yarn coverage

# Deploy to PR environment
deploy pr:
  stage: integration
  environment:
    name: pr/$CI_COMMIT_REF_NAME
    url: http://pr-$CI_COMMIT_REF_SLUG-wcn.bscode.net
    on_stop: delete pr
  only:
    - branches
  except:
    - master
  tags: [ shell ]
  script:
    - rsync -av --delete dist/app/ /var/opt/gitlab/nginx/www/$APP_DEPLOY_SLUG/
    - rsync -av --delete coverage/ /var/opt/gitlab/nginx/www/$APP_DEPLOY_SLUG/coverage/
    - |
      curl --request POST --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" "https://bscode.net/api/v4/projects/$CI_PROJECT_ID/statuses/$CI_COMMIT_SHA?name=Coverage%20Report&state=success&target_url=https://$APP_DEPLOY_SLUG/coverage"

# Job which deletes the PR environment
delete pr:
  stage: integration
  environment:
    name: pr/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  tags: [ shell ]
  script:
    - rm -rf /var/opt/gitlab/nginx/www/$APP_DEPLOY_SLUG

deploy dev:
  stage: deploy
  environment:
    name: dev
    url: https://dev-wcn.bscode.net/
  only:
    - master
  tags: [ shell ]
  script:
    - rsync -av --delete dist /var/opt/gitlab/nginx/www/dev-wcn.bscode.net
