version: 2
jobs:
  build:
#    working_directory: ~/foo-bar
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn versions && npm version

      # Install dependencies
      # Note: frozen-lockfile to make sure yarn.lock is in sync (otherwise fail, developer must commit latest yarn.lock)
      - run: yarn install --frozen-lockfile

      - run: yarn test:ci --progress=false
      - run: yarn build:prod --progress=false
      - run: yarn build:poc --progress=false
      - run: yarn lint

      - deploy:
          name: Deploy DEV
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn deploy
              yarn deploy:poc
            fi
      - deploy:
          name: Deploy LIVE
          command: |
            if [ "${CIRCLE_BRANCH}" == "live" ]; then
              yarn deploy:prod
            fi
